### ISSUE TITLE
sara failed to build with 4.15-rc8

### ISSUE THREAD

**Issue by Mdyrl7777777** [smeso/sara#1]
I used https://github.com/smeso/sara/tree/sarav4
Kernel 4.15-rc8 + [linux-hardened patches](https://github.com/copperhead/linux-hardened/tree/4.15) + some extras
gcc version 7.2.1 20171224
Archlinux
```
In file included from ./arch/x86/include/asm/atomic.h:5:0,
                 from ./include/linux/atomic.h:5,
                 from ./include/linux/dcache.h:5,
                 from security/sara/utils.c:12:
security/sara/utils.c: In function ‘get_current_path’:
./include/linux/compiler.h:324:38: error: call to ‘__compiletime_assert_86’ declared with attribute error: BUILD_BUG_ON failed: sizeof(*buf) != TASK_COMM_LEN
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                      ^
./include/linux/compiler.h:304:4: note: in definition of macro ‘__compiletime_assert’
    prefix ## suffix();    \
    ^~~~~~
./include/linux/compiler.h:324:2: note: in expansion of macro ‘_compiletime_assert’
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:47:37: note: in expansion of macro ‘compiletime_assert’
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:71:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
  BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
  ^~~~~~~~~~~~~~~~
./include/linux/sched.h:1502:2: note: in expansion of macro ‘BUILD_BUG_ON’
  BUILD_BUG_ON(sizeof(buf) != TASK_COMM_LEN); \
  ^~~~~~~~~~~~
security/sara/utils.c:86:3: note: in expansion of macro ‘get_task_comm’
   get_task_comm(*buf, current);
   ^~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:310: security/sara/utils.o] Error 1
make[1]: *** [scripts/Makefile.build:569: security/sara] Error 2
make: *** [Makefile:1018: security] Error 2
make: *** Waiting for unfinished jobs....

```

**Comment by smeso** [comment]
This bug, introduced in 3756f64, should be fixed by 1225233f7.
Thank you very much for reporting :)

**Comment by Mdyrl7777777** [comment]
It's working now, thank you.
