### ISSUE TITLE
SARA fails to build with linux 4.19-rc1

### ISSUE THREAD

**Issue by Mdyrl7777777** [smeso/sara#5]
```
  CC      security/sara/wxprot.o
In file included from security/sara/wxprot.c:21:
security/sara/wxprot.c:837:27: error: initialization of ‘int (*)(struct file *)’ from incompatible pointer type ‘int (*)(struct file *, const struct cred *)’ [-Werror=incompatible-pointer-types]
  LSM_HOOK_INIT(file_open, sara_file_open),
                           ^~~~~~~~~~~~~~
./include/linux/lsm_hooks.h:2053:57: note: in definition of macro ‘LSM_HOOK_INIT’
  { .head = &security_hook_heads.HEAD, .hook = { .HEAD = HOOK } }
                                                         ^~~~
security/sara/wxprot.c:837:27: note: (near initialization for ‘wxprot_hooks[4].hook.file_open’)
  LSM_HOOK_INIT(file_open, sara_file_open),
                           ^~~~~~~~~~~~~~
./include/linux/lsm_hooks.h:2053:57: note: in definition of macro ‘LSM_HOOK_INIT’
  { .head = &security_hook_heads.HEAD, .hook = { .HEAD = HOOK } }
                                                         ^~~~
  CC [M]  arch/x86/kvm/../../../virt/kvm/async_pf.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:308: security/sara/wxprot.o] Error 1
make[1]: *** [scripts/Makefile.build:548: security/sara] Error 2
make: *** [Makefile:1060: security] Error 2
make: *** Waiting for unfinished jobs....

```

**Comment by Mdyrl7777777** [comment]
Latest update fixed this issue. Thank you.
